
[{"author": "Unknown", "date": "Postbyyorik»Sun Dec 29, 2013 9:48 pm", "content": "If you think you found a bug in FreeCAD, you can help greatly by reporting that bug to the FreeCAD developers on the FreeCAD issues tracker athttps://github.com/FreeCAD/FreeCAD/issues.Bugs reported here on the forum can be easily overlooked or missed by developers, while on the tracker they are sure to stay in the queue until a developer looks at it.However, if well-made bug reports can help a lot and make the problem very easy to solve, bad bug reports can do the opposite: They can make the developer spend many unnecessary hours on the problem.Such bad reports are therefore often treated with the lowest possible priority, and you might not see your bug fixed.So, it is important to follow these guidelines when submitting a bug on the tracker:1.Make sure you use the latest development version to reproduce the bug.
The development branches are usually far from being experimental and they contain all the bugfixes since the last stable version. Your bug may be already fixed.The latest development version can be found onhttps://github.com/FreeCAD/FreeCAD-Bund ...kly-builds.2.Make sure that what you found is a bug.The definition of a bug is this: Something that is not working, but for which you are sure that it should be working (for example it worked in the past, or it is advertised on the FreeCAD documentation wiki).
Otherwise, it might be simply that what you want is not implemented, or maybe you are doing something wrong.3.Discuss the problem on the Help forum first!This should be donebeforecreating a ticket in the bugtracker, for several reasons: It may not be a bug after all and you will get advice how to proceed; developer time is precious and a discussion here in the forum will produce far better tickets; the helpers in the forum become aware of the bug; you may be offered a workaround until the bug is fixed.4.Make sure your bug can be reproduced. This is the most important rule.If the developer cannot reproduce your problem on his machine, he will not be able to fix it.So you must give an exact step-by-step procedure that the developer must follow to see your bug happen.For example:1.Open FreeCAD2.Press the \"create new document\" button3.Switch to the Part workbench4.Press the \"Create cube\" button5.FreeCAD crashes5.Always include your FreeCAD version information.
You can easily copy/paste all the needed information by using the \"Copy to clipboard\" button in FreeCAD, in menu Help -> About FreeCAD. You can then paste that information in your bug report.6.Include all possible FreeCAD error messages.When something wrong happens in FreeCAD, error messages are often printed, that can give precious information to the developer about what happened.The two places you should check for such error messages in FreeCAD are the Report window (menu View->Panels->Report view), the python console (menu View->Views->Python console).Make sure to include as much error text as possible.7.If possible, also check the terminal and the FreeCAD log for error messages.A third possible place to look for error messages is the system terminal, which you can get on Linux and Mac systems by opening a terminal, and launching FreeCAD from it, by typing \"freecad\" <enter>.A fourth place to look for error messages is the FreeCAD log.
To produce such a log, you must either run FreeCAD from a terminal by running \"freecad -l\" or change the properties of your FreeCAD launch icon, and use \"freecad -l\" instead of \"freecad\". After running and closing (or crashing) FreeCAD, you will find a file called freecad.log in your FreeCAD user directory (/home/youruser/.FreeCAD on linux and mac, C:/users/youruser/ApplicationData/FreeCAD on windows).8.Stay cool and patient.We all know bugs are annoying, but nobody is here to serve you, developers will work on solving bugs when they have time to do so, and efficient bug fixing depends largely on how helpful people submitting bugs are.By following the above rules, you'll be doing a very good job when submitting your bug, and make sure your bug is treated in the best possible manner.
Thanks!"}, {"author": "Unknown", "date": "Postbyyorik»Sun Dec 29, 2013 9:56 pm", "content": "I now added a text on top of the bug submit page on the mantis tracker, that links here."}, {"author": "Freakinbob", "date": "PostbyFreakinbob»Thu Jul 23, 2015 4:39 pm", "content": "In theHelp FreeCADsection of the documentation wicki it reads:Report bugs and ask for interesting featuresThe place to report bugs and suggest new features is the FreeCAD TrackerNot only would it not let me create an account, because it did not ask me to create a password which logon requires, nor did it send me a confirmation email at all with or without an auto generated password.
I tried to log on anonymously, but it did not indicate weather I was logged on or not, and there was no place to report a bug nor make suggestions.Here you explain what a bug is, and what is not, but neither here nor there did I see anything about feature requests.Anyhow since I want to suggest some features and make a few suggestions, may I start with this:Fix the above mentioned issues, and be more clear on where to do what.
It would also make sense to have a separate feature request topic area on the forums all together, as well as separating usage \"How to's, tips and tricks\" from \"How to get stuff to work, when it does not work right or as expected\"."}, {"author": "Unknown", "date": "Postbyjmaustpc»Sun Jan 31, 2016 2:23 pm", "content": "Freakinbob wrote:In the Help FreeCAD section of the documentation wicki it reads:For future reference if someone finds an error or something that needs updating in the wiki,....please provide the URL so that we can just click on it and be sure that we have gone to the correct part of the wiki.
The section of the wiki referred to in the above post had been correct once but was just way out of date.I have updated the wiki now.Bugs should be posted and discussed in the Help forum first and if confirmed then a good quality ticket with all the information can be created in the bug tracker.Feature requests should be discussed in the Open discussion forum."}, {"author": "jon_bondy", "date": "Postbyjon_bondy»Sat Jul 30, 2016 12:28 pm", "content": "For Windows users, Yorik's post says that the FreeCAD log file may be found here: C:/users/youruser/ApplicationData/FreeCADI found the log here on Windows 10: C:/users/youruser/AppData/Roaming/FreeCADJon"}, {"author": "EGlaz", "date": "PostbyEGlaz»Wed Feb 01, 2017 11:11 am", "content": "Hello!I want post a bug, but i can not register in bug tracker because \"visual captcha\" doesn't show anything!
I have tried Win & Linux with Firefox, IE, Chromium - all the same.Visoble captcha.png (25.86 KiB) Viewed 765328 times"}, {"author": "Unknown", "date": "Postbyyorik»Wed Feb 01, 2017 6:45 pm", "content": "EGlaz wrote:\"visual captcha\" doesn't show anythingThere is indeed a problem with the mantis catchpa, but I couldn't find what's wrong... Anyway, we'll upgrade the mantis software to the new 2.0 version ASAP, hopefully that error will be gone then."}, {"author": "Unknown", "date": "PostbyKunda1»Tue Oct 02, 2018 9:50 pm", "content": "Yorik, I propose the following change to the Guidelines.I've just increased the font size of each step.(I can delete this post after this discussion is over)yorikwrote:↑Sun Dec 29, 2013 9:48 pmIf you think you found a bug in FreeCAD, you can help greatly by reporting that bug to the FreeCAD developers on the FreeCAD bug tracker athttp://www.freecadweb.org/tracker/.
Bugs reported here on the forum can be easily overlooked or missed by developers, while on the tracker they are sure to stay in the queue until a developer looks at it.However, if well-made bug reports can help a lot and make the problem very easy to solve, bad bug reports can do the opposite: They can make the developer spend many unnecessary hours on the problem. Such bad reports are therefore often treated with the lowest possible priority, and you might not see your bug fixed.So, it is important to follow these guidelines when submitting a bug on the tracker:1.Make sure that what you found is a bug.The definition of a bug is this: Something that is not working, but for which you are sure that it should be working (for example it worked in the past, or it is advertised on the FreeCAD documentation wiki).Otherwise, it might be simply that what you want is not implemented, or maybe you are doing something wrong.2.If you are unsure, discuss the problem on the forum first.
Open a new topic here on the forum, in the help section, and ask if what you found is a bug. Other users will surely be able to help you determining what you should do.3.Make sure your bug can be reproduced.This is the most important rule.If the developer cannot reproduce your problem on his machine, he will not be able to fix it.So you must give an exact step-by-step procedure that the developer must follow to see your bug happen.For example:1.Open FreeCAD2.Press the \"create new document\" button3.Switch to the Part workbench4.Press the \"Create cube\" button5.FreeCAD crashes4.Always include your FreeCAD version information.You can easily copy/paste all the needed information by using the \"Copy to clipboard\" button in FreeCAD, in menu Help -> About FreeCAD.You can then paste that information in your bug report.5.Include all possible FreeCAD error messages.
When something wrong happens in FreeCAD, error messages are often printed, that can give precious information to the developer about what happened. The two places you should check for such error messages in FreeCAD are the Report window (menu View->Views->Report view), the python console (menu View->Views->Python console).Make sure to include as much error text as possible.6.If possible, also check the terminal and the freecad log for error messages.A third possible place to look for error messages is the system terminal, which you can get on linux and mac systems by opening a terminal, and launching FreeCAD from it, by typing \"freecad\" <enter>.A fourth place to look for error messages is the FreeCAD log.To produce such a log, you must either run FreeCAD from a terminal by running \"freecad -l\" or change the properties of your FreeCAD launch icon, and use \"freecad -l\" instead of \"freecad\".
After running and closing (or crashing) FreeCAD, you will find a file called freecad.log in your FreeCAD user directory (/home/youruser/.FreeCAD on linux and mac, C:/users/youruser/ApplicationData/FreeCAD on windows).7. Stay cool and patient.We all know bugs are annoying, but nobody is here to serve you, developers will work on solving bugs when they have time to do so, and efficient bug fixing depends largely on how helpful people submitting bugs are.By following the above rules, you'll be doing a very good job when submitting your bug, and make sure your bug is treated in the best possible manner.Thanks!"}, {"author": "Unknown", "date": "Postbychrisb»Tue Oct 02, 2018 9:59 pm", "content": "Since I've seen how easy the very big banner in the bug tracker is ignored, I'm afraid we cannot expect much from increasing the font, but we can give it a try.Perhaps it doesn't have to bethatbig.But there is something more important:We require a forum discussion before opening a ticket.
So point two should read2. Discuss the problem on the forum first!"}, {"author": "Unknown", "date": "PostbyKunda1»Tue Oct 02, 2018 10:23 pm", "content": "chrisbwrote:↑Tue Oct 02, 2018 9:59 pmSince I've seen how easy the very big banner in the bug tracker is ignored, I'm afraid we cannot expect much from increasing the font, but we can give it a try.Perhaps it doesn't have to bethatbig.But there is something more important:We require a forum discussion before opening a ticket.So point two should read2.Discuss the problem on the forum first!Yea, I agree with tweaking #2and I still think bolded text is a good way to go."}, {"author": "Unknown", "date": "Postbychrisb»Tue Oct 02, 2018 10:35 pm", "content": "Kunda1wrote:↑Tue Oct 02, 2018 10:23 pmand I still think bolded text is a good way to go....whatever helps to improve awareness."}, {"author": "Unknown", "date": "Postbysgrogan»Tue Oct 02, 2018 10:40 pm", "content": "chrisbwrote:↑Tue Oct 02, 2018 9:59 pm2.
Discuss the problem on the forum first!Maybe we could add anwhy?link?I don't know the words, but, \"help us triage your bug so it gets fixed. Developer time is precious\" etc.?"}, {"author": "Unknown", "date": "PostbyKunda1»Mon Oct 08, 2018 2:27 pm", "content": "sgroganwrote:↑Tue Oct 02, 2018 10:40 pmchrisbwrote:↑Tue Oct 02, 2018 9:59 pm2.Discuss the problem on the forum first!Maybe we could add anwhy?link?I don't know the words, but, \"help us triage your bug so it gets fixed.Developer time is precious\" etc.?I think this is also a valid request.Do we have consensus on what I'm proposing inhttps://forum.freecadweb.org/viewtopic....
36#p259976"}, {"author": "NormandC", "date": "PostbyNormandC»Mon Oct 08, 2018 6:34 pm", "content": "Fine with me."}, {"author": "Unknown", "date": "Postbychrisb»Mon Oct 08, 2018 8:18 pm", "content": "NormandCwrote:↑Mon Oct 08, 2018 6:34 pmFine with me.Me too."}, {"author": "Unknown", "date": "Postbysgrogan»Mon Oct 08, 2018 8:35 pm", "content": "Kunda1wrote:↑Mon Oct 08, 2018 2:27 pmDo we have consensus on what I'm proposing inhttps://forum.freecadweb.org/viewtopic. ...36#p259976I would tweak #2 as suggested by chrisb.Even if the user is sure, we want to test on other OS/Distros to refine the bug report."}, {"author": "ooveif9", "date": "Postbyooveif9»Sat Aug 03, 2019 5:45 pm", "content": "yorikwrote:↑Sun Dec 29, 2013 9:48 pm1.Make sure that what you found is a bug.The definition of a bug is this: Something that is not working, but for which you are sure that it should be working (for example it worked in the past, or it is advertised on the FreeCAD documentation wiki).
Otherwise, it might be simply that what you want is not implemented, or maybe you are doing something wrong.Please clarify your bug definition. If FreeCAD crashes because I do something wrong, is that a bug or not?Should it be reported?Thanks."}, {"author": "Unknown", "date": "PostbyGeneFC»Sat Aug 03, 2019 9:25 pm", "content": "Following the directions in the first post of this topic is still the correct method for \"bugs\".If you get to the third box, go ahead and create a topic in the Help fourm.The responders will either help find your error or will agree that the crash is really a bug.Don't go straight to the Mantis tracker before discussing on the forum.A crash should never happen, whether due to user error or a bug.
But of course crashes do happen because it is very difficult to predict every sort of error that a user might make.Gene"}, {"author": "Unknown", "date": "Postbychrisb»Sat Aug 03, 2019 10:08 pm", "content": "sgroganwrote:↑Tue Oct 02, 2018 10:40 pmchrisbwrote:↑Tue Oct 02, 2018 9:59 pm2. Discuss the problem on the forum first!Maybe we could add anwhy?link?I don't know the words, but, \"help us triage your bug so it gets fixed.Developer time is precious\" etc.?Proposal for point 2:2.
Discuss the problem on the forum first!This should be donebeforecreating a ticket in the bugtracker, for several reasons: It may not be a bug after all and you will get advice how to proceed; developer time is precious and a discussion here in the forum will produce far better tickets; you may be offered a workaround until the bug is fixed."}, {"author": "freman", "date": "Postbyfreman»Sat Oct 12, 2019 3:57 am", "content": "and I still think bolded text is a good way to go.Yeah, if shouting doesn't work, shout louder !Agree with Chris , making it conditional invites folks to ignore it."},
{
    "author": "blw",
    "date": "Postbyblw\u00bbMon Dec 30, 2024 9:24 am",
    "content": "This one is very repeatable, and I am pretty sure it's a bug. In this form, it is easy to avoid, but if for some reason you do it by accident (as I first did), it's a very sudden and unexpected crash.Code:Select allOS: macOS 15.2\nArchitecture: arm64\nVersion: 1.0.0.39109 (Git) Conda\nBuild type: Release\nBranch: (HEAD detached at 1.0.0)\nHash: 2fcc5317fe3aee96ca73475986a577719fc78e20\nPython 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1\nLocale: C/Default (C)\nStylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion\nInstalled mods: \n  * PieMenu 1.11.2\n  * ArchTextures\n  * A2plus 0.4.68\n  * lattice2 1.0.0\n  * sheetmetal 0.6.13\n  * LCInterlocking\n  * Curves 0.6.52Create a new document, go to Part Design. Create a body, then a sketch on XY plane. Choose Create Ellipse from Center. On the origin, draw a ellipse going to the right by 0.9mm and click. It will put a few characters in gibberish in the lower left corner of the main window. If you click anywhere in the window, you will get the attached crash."
},
{
    "author": "thomas-neemann",
    "date": "Postbythomas-neemann\u00bbMon Dec 30, 2024 9:34 am",
    "content": "blwwrote:\u2191Mon Dec 30, 2024 9:24 amcan you upload your file?"
},
{
    "author": "xemul",
    "date": "Postbyxemul\u00bbMon Dec 30, 2024 12:22 pm",
    "content": "blwwrote:\u2191Mon Dec 30, 2024 9:24 am... Choose Create Ellipse from Center.The crash occurs in 39109, 39416, 39673 builds.After defining the center of the ellipse somewhere, an input field appears with default \"nan mm\" (NotANumber)Snip macro screenshot-93a6a5.png (11.39 KiB) Viewed 19 timesIf you enter any reasonable value instead of \"nan\", no crash will occur.38728 build don't crash but throws in the ReportViewCode:Select all15:15:57  pyException: Traceback (most recent call last):\n  File \"<string>\", line 4, in <module>\n<class 'NameError'>: name 'nan' is not defined\n15:15:57  Unnamed#Sketch: Failed to add ellipse\n15:15:57  Tool execution abortedNo problem with \"Ellipse by 3 points\""
},
{
    "author": "Unknown",
    "date": "Postbywmayer\u00bbMon Dec 30, 2024 12:46 pm",
    "content": "With v1.1 I get these error messages:Code:Select allSketcher constraint number 1 is malformed!\nUnhandled Base::Exception caught in GUIApplication::notify.\nThe error message is: Geometry element does not have solver information (possibly when trying to apply widget constraints)!\nExceptions must be caught before they go through Qt. Ignoring this will cause crashes on some systems.\nSketcher constraint number 1 is malformed!\nSketcher constraint number 3 is malformed!\nUnhandled exception in ViewProvider::eventCallback: Geometry element does not have solver information (possibly when trying to apply widget constraints)!\n(Event type: SoMouseButtonEvent, object type: SketcherGui::ViewProviderSketch)\nSketcher constraint number 1 is malformed!\nSketcher constraint number 3 is malformed!\nSketcher constraint number 5 is malformed!\nUnhandled exception in ViewProvider::eventCallback: Geometry element does not have solver information (possibly when trying to apply widget constraints)!\n(Event type: SoMouseButtonEvent, object type: SketcherGui::ViewProviderSketch)The crash reported by the OP is macOS specific only because there it's not allowed to let exceptions go through GUIApplication::notify."
},
    {
    "author": "NormandC",
    "date": "PostbyNormandC\u00bbMon Feb 20, 2012 11:43 pm",
    "content": "Welcome here, and thanks for your interest in FreeCAD! We are a small but active community of users and developers. We are eager to assist you, but please read the following before posting:Be nice to others!It is important to keep this forum a nice and respectful place. Be sure to read the FreeCADcode of conduct!Make sure your FreeCAD version is up to dateBug fix releases are published a few times a year as needed. Make sure you are using the latest version listed on theDownloadpage or from the even more currentdeveloper version.Search the forum firstChances are other users had the same problem as you before. The 2 most common questions are coveredhere. Also have a look at our exhaustiveFrequently asked questions, theFreeCAD Manualand theDocumentation.Please provide your FreeCAD version info - (scroll further down this page if you wish to see a video on how to do this created by Mario52)Open theHelp --> About FreeCADmenu then click on the \"Copy to clipboard\" button, and paste its content in the text input area. This will provide us valuable information on your exact version and revision number, your operating system as well as FreeCAD's internal libraries. (Mac users:the About FreeCAD menu is under the FreeCAD menu.)Please do not attach a screen capture instead of posting the Help > About FreeCAD information from the clipboard.Don't add your FreeCAD info or any other version data to your signature. When you change your signature, the forum software shows the updated signature in every post you ever made, obviously this means that over time your version data in a signature would become wrong for all your previous posts.Please provide a complete description of your problemThe best way to get quick and efficient help is to not spare any details. What workbench and tools are you using? What steps did you take? What was the result? If a question refers to a tutorial, add a link. If it is a video, use a link that contains the position where to start. This will avoid back-and-forth exchanges and save time for everybody.Add your FreeCAD file and/or screen capturesYour FreeCAD file (*.FCStd) can be useful to troubleshoot the problem, and screen captures can also be useful. Under the text input area, click on theAttachmentstab, then click on theAdd filesbutton. (Many different file formats are supported)Please don't zip your *.FCStd file, it is already zipped.Windows users:please do not attach screen captures in Word or PDF format. Use the Windows Snipping tool to save your capture as a PNG image. (Here's how)File attachments are limited to 1MB in size. If your *.FCStd file is too big to attach, you can use an online storage service (many are free like Google Drive, Microsoft OneDrive, Dropbox).Thanks for reading! And don't forget to thank those who helped you. We're all volunteers who dedicate some of our precious time to help others and thanks are always appreciated.Useful linksThe top rated errors and how to avoid themHow to report a bugHow to quote correctlyRevised 04/22/2017 based onthis topic. Thanks to bejant, chrisb, DeepSOIC, jmaustpc and sgrogan."
},
{
    "author": "Unknown",
    "date": "Postbyjmaustpc\u00bbWed Oct 01, 2014 12:39 pm",
    "content": "How to \"QUOTE\" another post or part of another postYou make it hard to follow when you \"quote\" without the user name, particularly within complex topics.If you quote another user properly, it includes their user name within the quote and the system informs the other user that they have been quoted.If you have opened a posting window, then just highlight the text you want to quote and click on the \"quote\" button associated with the post you are quoting...then you will get a quote with the user name automatically included, and it will only include the highlighted text.It is good style to quote just what you are directly referring to. You can concentrate on the important parts and the forum regulars have probably read the previous posts anyway and don't want to read the same over and over again. If somebody wants to read more, he can use the small up arrow link which leads to the post.If you have nothing highlighted ...then the quote button associated with a specific post will quote the entire post.If you do not first open a posting window and simply click on the quote button associated with another post, it will open a posting window and insert the complete post as a \"quote\".Partial quoting of highlighted text only works if you first open a posting window."
},
{
    "author": "Unknown",
    "date": "Postbyjmaustpc\u00bbFri Apr 01, 2016 3:02 pm",
    "content": "Anti-Spam MeasuresIn recent years, spam has forced us to introduce the following.....Anonymous posting had to be disallowedThat means you now have to register before you can post messages on the FreeCAD forums.New users can not send a PMA new user can not send a Private Message (PM) to other users until after their first post has been approved.First posts are hidden until approvedSpammers started registering and then filling the forums with spam, so now we have been forced to hide all first posts until a moderator or admin has approved the first post, at least that means that the public does not see these spam posts before they are removed.New users can only make one postThen the spammers started flooding us with huge numbers of first post, so we were forced to only allow new users to post once, until a pre-set time has expired or their first post has been approved."
},
{
    "author": "NormandC",
    "date": "PostbyNormandC\u00bbSat Apr 22, 2017 7:37 pm",
    "content": "Most Commonly Asked QuestionsQ. I exported my model to STL or DXF but all the holes are filled up and fillets are missing.A.Don't select All or use Ctrl + A to export for 3D printing. You typically only need to select the last object at the bottom of the Model tree, or in the case of a PartDesign Body, select the Body itself.Q. The feature (Pad or Pocket) I added doesn't show.A.Make sure that only the last element in the tree is visible. You can toggle visibility by selecting it in the tree and hitting the space bar. Invisible elements in the tree are greyed out."
},
{
    "author": "Unknown",
    "date": "Postbyjmaustpc\u00bbWed Aug 12, 2020 11:33 am",
    "content": "A short animated Gif video on how to access your FreeCAD version info (created by Mario52)...Open the Help --> About FreeCAD menu then click on the \"Copy to clipboard\" button, and paste its content in the text input area. This will provide us valuable information on your exact version and revision number, your operating system as well as FreeCAD's internal libraries. (Mac users: the About FreeCAD menu is under the FreeCAD menu.)Please do not attach a screen capture instead of posting the Help > About FreeCAD information from the clipboard. Don't add your FreeCAD info or any other version data to your signature. When you change your signature, the forum software shows the updated signature in every post you ever made, obviously this means that over time your version data in a signature would become wrong for all your previous posts.Copy_Info_FreeCAD2.gif (260.86 KiB) Viewed 907389 times"
},  {
    "author": "Unknown",
    "date": "Postbychrisb\u00bbWed Aug 29, 2018 6:38 am",
    "content": "This topic is locked. For comments go tohttps://forum.freecadweb.org/viewtopic.php?f=3&t=30574For modeling issues please refer to theFrequently asked questionsand theTroubleshooting modelsGeneral issuesFor fault finding it can be helpful to start FreeCAD with the additional commandline parameter--write-log, which creates a log file in your FreeCAD directory, see theDebuggingpage where to find it. If you are asked to show it in the forum, please put the contents in code tags using the </> button.Errors when writing files to network devicesThis can happen due to the file saving technique where the file is in a first step written with a unique new name and is later renamed. Seeviewtopic.php?t=76113#p661093for more infos (German).Solution:- open Tools->Edit parameters- navigate to BaseApp > Preferences > Document- create a new boolean key BackupPolicy and set its value to false.Errors in Step exports with FreeCAD 0.19Solution:upgrade to FreeCAD 0.19.4 or to a current 0.20 version.All self compiled versions and packages created by other distributionsThere are issues when using Python 3.10.x. If you compile yourself you may have to use Python 3.8 instead. For further details seehttps://github.com/coin3d/pivy/issues/88.If theAddonManagercomplains of no connection to GithubTo test the connection between FreeCAD and Github (where we currently host many Addons, type the following in to thePython consoleCode:Select allimport urllib.request\nr = urllib.request.urlopen(\"https://api.github.com/zen\")\nr.read()A reply likeb'Design for failure.'indicates the connection is working.LinuxIcons and/or text appear cut(added 2022-09-08)This issue is usually related to dpi configuration on Linux, often observed in environments using xfce or xfce settings. Seehttps://forum.freecadweb.org/viewtopic. ... 8&p=622644for an example screenshot.Solutionopen xfce appearance settings, go to the Fonts tab and unset any custom dpi settings (or try setting to 96 if this does not work)If this still doesn't work, you can set the following on the command line before starting FreeCAD:Code:Select allQT_AUTO_SCREEN_SCALE_FACTOR=0 freecadSee e.g.https://forum.freecadweb.org/viewtopic. ... 69#p648269.FreeCAD starts with the splash screen, but doesn't show anything further.Workaround:If starting from the command line one of the following errors (and more) is shown:Code:Select alllibGL error: MESA-LOADER: failed to open radeonsi:Code:Select alllibGL error: MESA-LOADER: failed to open iris:Code:Select alllibGL error: failed to load driver: swrastMore errors involvinglibstdc++.soar likely.SolutionBefore starting from the command line, set the environment variableLD_PRELOAD. You may have to adapt the following to match your system:Code:Select allLD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ./FreeCAD_weekly-builds-27936-Linux-Conda_glibc2.12-x86_64.AppImageFreecad crashes on loading, sometimes loads and crashes almost immediately afterwards, sometimes opens for a short time but soon crashes.(tested on 0.20)Hardware affected: nvidia graphic cardsProblem: When running from terminal, might report:Code:Select all./FreeCAD_weekly-builds-26720-Linux-Conda_glibc2.12-x86_64.AppImage\nFreeCAD 0.20, Libs: 0.20R26720 (Git)\n... clipped...\nnouveau: kernel rejected pushbuf: No such file or directory\nnouveau: ch5: krec 0 pushes 0 bufs 1 relocs 0\nnouveau: ch5: buf 00000000 00000002 00000004 00000004 00000000 0x7f2c0812b000 0x30000 0x80000\nProgram received signal SIGSEGV, Segmentation fault.\nProgram received signal SIGSEGV, Segmentation fault.\n#0  /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f2c122a6210]\n/tmp/.mount_FreeCAYIY0GE/AppRun: line 41:  6296 Segmentation fault      ${MAIN} \"$@\"SolutionSometimes just updating nvidia drivers works, but the best/proven working option (if possible) is to change to \"Use Software OpenGL\" in Preferences.In the case where FreeCAD doesn't start the GUI so that the preferences are unavailable, this option can be set via the following command without starting the GUI:Code:Select all./FreeCAD.AppImage freecadcmd\nFreeCAD.ParamGet(\"User parameter:BaseApp/Preferences/OpenGL\").SetBool(\"UseSoftwareOpenGL\", 1)\nFreeCAD.saveParameter()This is a Windows generated user.cfg where \"Use Software OpenGL\" is checked:user.cfg(8.96 KiB) Downloaded 464 timesForum Discussion(links to specific posts):https://forum.freecadweb.org/viewtopic. ... 25#p558116https://forum.freecadweb.org/viewtopic. ... 80#p546204Errors occur when creating a Path Job, other workbenches work wellThe error message isCode:Select all09:45:18  PathJobGui.ERROR: function takes exactly 2 arguments (1 given)\n09:45:18  Traceback (most recent call last):\n09:45:18    File \"/usr/share/freecad-daily/Mod/Path/PathScripts/PathJobGui.py\", line 1363, in Create\n    obj = PathJob.Create('Job', base, template)\n09:45:18    File \"/usr/share/freecad-daily/Mod/Path/PathScripts/PathJob.py\", line 509, in Create\n    obj.Proxy = ObjectJob(obj, models, templateFile)\n09:45:18    File \"/usr/share/freecad-daily/Mod/Path/PathScripts/PathJob.py\", line 155, in __init__\n    self.setupBaseModel(obj, models)\n09:45:18    File \"/usr/share/freecad-daily/Mod/Path/PathScripts/PathJob.py\", line 190, in setupBaseModel\n    model.addObjects([createModelResourceClone(obj, base) for base in models])\n09:45:18    File \"/usr/share/freecad-daily/Mod/Path/PathScripts/PathJob.py\", line 190, in <listcomp>\n    model.addObjects([createModelResourceClone(obj, base) for base in models])\n09:45:18    File \"/usr/share/freecad-daily/Mod/Path/PathScripts/PathJob.py\", line 98, in createModelResourceClone\n    return createResourceClone(obj, orig, 'Model', 'BaseGeometry')\n09:45:18    File \"/usr/share/freecad-daily/Mod/Path/PathScripts/PathJob.py\", line 84, in createResourceClone\n    clone = Draft.clone(orig)\n09:45:18    File \"/usr/share/freecad-daily/Mod/Draft/draftmake/make_clone.py\", line 111, in make_clone\n    cl.addExtension(\"Part::AttachExtensionPython\")\n09:45:18  TypeError: function takes exactly 2 arguments (1 given)SolutionThis is caused by multiple Python versions. According tohttps://forum.freecadweb.org/viewtopic. ... 69#p495752this can be fixed:remove freecad-python3 libfreecad-python3-0.18reinstall freecad-daily-python3 libfreecad-daily-python3-0.19AppImage fails to open with a segmentation fault; observed on a Mageia system, seehttps://forum.freecadweb.org/viewtopic.php?f=8&t=50118.The error message isCode:Select allLoading Assembly4 WorkBench\nProgram received signal SIGSEGV, Segmentation fault.\n#0  /lib64/libc.so.6(+0x3caf0) [0x7fdc530c6af0]\n#1  /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libQt5XcbQpa.so.5(+0x56b27) [0x7fdc4cc9ab27]\n#2  /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libQt5XcbQpa.so.5(+0x56b47) [0x7fdc4cc9ab47]\n#3  0x7fdc4cc9a575 in QXcbNativeInterface::addHandler(QXcbNativeInterfaceHandler*) from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libQt5XcbQpa.so.5+0x1f\n#4  /usr/lib64/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so(+0xd179) [0x7fdc47f7f179]\n#5  /usr/lib64/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so(+0x957a) [0x7fdc47f7b57a]\n#6  0x7fdc4cc869d6 in QXcbConnection::glIntegration() const from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libQt5XcbQpa.so.5+0x33c\n#7  0x7fdc4cc877e6 in QXcbIntegration::createPlatformOpenGLContext(QOpenGLContext*) const from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libQt5XcbQpa.so.5+0x22\n#8  0x7fdc539b53e9 in QOpenGLContext::create() from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libQt5Gui.so.5+0x2f\n#9  0x7fdc5398fde9 in QGuiApplicationPrivate::init() from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libQt5Gui.so.5+0x4b9\n#10  0x7fdc53e18c13 in QApplicationPrivate::init() from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libQt5Widgets.so.5+0x9\n#11  0x7fdc5592d1c2 in Gui::GUIApplicationNativeEventAware::GUIApplicationNativeEventAware(int&, char**) from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libFreeCADGui.so+0x12\n#12  0x7fdc5592ba72 in Gui::GUIApplication::GUIApplication(int&, char**) from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libFreeCADGui.so+0x22\n#13  0x7fdc5592c94a in Gui::GUISingleApplication::GUISingleApplication(int&, char**) from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libFreeCADGui.so+0x2a\n#14  0x7fdc558a17b4 in Gui::Application::runApplication() from /tmp/.mount_FreeCAwBx8F0/usr/bin/../lib/libFreeCADGui.so+0xb4\n#15  /tmp/.mount_FreeCAwBx8F0/usr/bin/freecad(+0x37cd) [0x5594ce4147cd]\n#16  /lib64/libc.so.6(__libc_start_main+0xeb) [0x7fdc530b0b0b]\n#17  /tmp/.mount_FreeCAwBx8F0/usr/bin/freecad(+0x4521) [0x5594ce415521]SolutionBefore starting unset the environment variable QT_PLUGIN_PATHCode:Select allunset QT_PLUGIN_PATHThis could be done in a special batch file or on one of the startup scripts.Ubuntu does not show *.FCStd files and does not use the file extension on savingThis is an issue with the system file selection dialog. From another topic:wmayerwrote:\u2191Sun Jan 27, 2019 11:23 amThe problem is somehow with the native file dialog on some DEs (Desktop Environments).The easiest would be to upgrade to v0.18 where we have added an option to change atruntime between the native and Qt file dialog.Workaround:1. Open theParameter editorfrom the Tools menu2. Navigate toBaseApp/Preferences/Dialog3. Create a boolean parameter named:DontUseNativeDialogand set it to true.Startup fails on Debian based system like Ubuntu, Debian, Mint, ...FreeCAD startup may fail with the messageCode:Select allfailed to create drawable\n[xcb] Unknown sequence number while processing queue\n[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called\n[xcb] Aborting, sorry about that.\nfreecad: xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.\nAbortedWorkaround:Launch FreeCAD from the command line terminal:gntechwrote:\u2191Thu Apr 12, 2018 6:04 pmA workaround is to disable DRI3 just for FreeCAD by launching FreeCAD from the terminal with the following command.Code:Select allLIBGL_DRI3_DISABLE=true freecadCrash on Debian based systems importing SVGHint from NormandC: The current PPAs fix this by upgrading some dependencies. Users who previously implemented Chris_G's fix mentioned below should revert the change (unlock the expat/libexpat1 packages and update them to the version in the Ubuntu 18.04/18.10 repo) for the PPA update to succeed.Outdated message:FreeCAD can crash when importing SVG files with a message likejalarwrote:\u2191Wed Jan 10, 2018 1:19 pmCode:Select allopenat(AT_FDCWD, \"/path-to-file.svg\", O_RDONLY) = 27\nfstat(27, {st_mode=S_IFREG|0644, st_size=2234752, ...}) = 0\n--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x3a9} ---\nwrite(2, \"\\33[1;31m\", 7)                = 7\nwrite(2, \"Program received signal SIGSEGV,\"..., 53Program received signal SIGSEGV, Segmentation fault.\n) = 53\n\n#0  /lib/x86_64-linux-gnu<br />\n/libc.so.6(+0x37140) [0x7fd97f382140]\n#1  /lib/x86_64-linux-gnu/libexpat.so.1(XML_SetHashSalt+0x1b) [0x7fd976c411cb]\n#2  /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so(+0x6968) [0x7fd90487a968]\n...Workaround:As a solution some libraries have to be installed manually:Chris_Gwrote:\u2191Thu Apr 19, 2018 8:45 amThe packages from Ubuntu xenial work fine :https://packages.ubuntu.com/xenial/expathttps://packages.ubuntu.com/xenial/libexpat1I have also this one, but I don't know if it is really needed :https://packages.ubuntu.com/xenial/libexpat1-devThen in the folder where you downloaded the packages :Code:Select allsudo dpkg -i ./expat_2.1.0-7ubuntu0.16.04.3_amd64.deb\nsudo echo expat hold | sudo dpkg --set-selections\nsudo dpkg -i ./libexpat1_2.1.0-7ubuntu0.16.04.3_amd64.deb\nsudo echo libexpat1 hold | sudo dpkg --set-selections\nsudo dpkg -i ./libexpat1-dev_2.1.0-7ubuntu0.16.04.3_amd64.deb\nsudo echo libexpat1-dev hold | sudo dpkg --set-selectionsSpacenav Mouse IssuesSome users are reporting that they can't use their3Dconnexion input deviceson different Linux distros.(ref:thread 1,thread 2)Workaround:A user seems to have fixed it, seems like it was permissions issue:https://forum.freecadweb.org/viewtopic. ... 27#p341327Crash when loading/creating a file and other problems when using Wayland display serverSeehttps://forum.freecadweb.org/viewtopic.php?f=3&t=75251When trying to open or create a document, it crashes immediately when started as normal user, but runs well as user root.Code:Select allProgram received signal SIGSEGV, Segmentation fault.\n#0  /lib/x86_64-linux-gnu/libc.so.6(+0x38d60) [0x7fdd66cefd60]\n#1  /lib/x86_64-linux-gnu/libX11.so.6(XDefaultScreenOfDisplay+0) [0x7fdd64e0f2c0]\n...\n#5  0x7fdd666ff2a8 in SoGLRenderActionP::isDirectRendering(SoState const*) const from /lib/x86_64-linux-gnu/libCoin.so.80c+0x48\n...SolutionBe sure that the XWayland package is installed and the environment variable QT_QPA_PLATFORM is not set towayland.Crash when loading a fileSeehttps://forum.freecadweb.org/viewtopic.php?f=8&t=49849.When loading a FreeCAD file the program crashes before displaying the model with the messageCode:Select allProgram received signal SIGSEGV, Segmentation fault.\n#0  /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1b4bd56210]\n#1  /usr/lib/x86_64-linux-gnu/dri/iris_dri.so(+0xb21c14) [0x7f1b3ce4dc14]\n...\n#5  /usr/lib/x86_64-linux-gnu/dri/iris_dri.so(+0x13c8d4) [0x7f1b3c4688d4]\n#6  0x7f1b4a8ac8d8 in QPlatformBackingStore::composeAndFlush(QWindow*, QRegion const&, QPoint const&, QPlatformTextureList*, bool) from /lib/x86_64-linux-gnu/libQt5Gui.so.5+0x198Workaround:Set the environment variableCode:Select allMESA_LOADER_DRIVER_OVERRIDE=i965Seehttps://askubuntu.com/questions/1254544 ... untu-20-04Crash on Arch Linux.Workaround:Downgrade Mesa versions:Code:Select allsudo pacman downgrade\nsudo downgrade mesaSelf compiled OpenCamLib OCL doesn't work, although compilation is successfulSolution:unlike in the Windows installation, the name of the directory shouldn't be named in uppercase letters, seehttps://forum.freecadweb.org/viewtopic. ... 96#p537059.ChromeBook / ChromeOSChromebook can rund the Linux versions of FreeCAD, e.g. the AppImage.Starting FreeCAD seems ok, but when trying to create or open file, it doesn't respond anymore.Workaround:Disable GPU acceleration. In a terminal setCode:Select allexport LIBGL_ALWAYS_SOFTWARE=1before starting FreeCAD. Look athttps://www.reddit.com/r/Crostini/comme ... n_per_app/to learn how to do it permanently.Correspondingforum post.WindowsFreeCAD doesn't start; the log shows an \"Access violation\" (added 2023-10-31)Workaround:Rename in FreeCAD_install_folder/bin/ openglsw32.dll to opengl32.dll.FreeCAD doesn't start when splash screen is disabled.(added 2023-04-03)Solution 1:Reset the complete configuration by deleting the fileuser.cfgSolution 2:Exit all running FreeCAD instances and search in the fileuser.cfgthe string \"ShowSplasher\" inCode:Select all<FCBool Name=\"ShowSplasher\" Value=\"0\"/>Change the value to 1 to enable the splash screen.FreeCAD not responding beyond splash screen when using multiple monitors.(added 2022-07-02)Solution:Stop the Nahimic service. The root cause has been established with the help of the Cura community seehttps://github.com/Ultimaker/Cura/issue ... 1200322553.See alsohttps://forum.freecadweb.org/viewtopic.php?f=3&t=69963orviewtopic.php?f=3&t=69071.Addon manager does not work on windows with special characters in the username.(added 2022-06-28)https://forum.freecadweb.org/viewtopic.php?f=3&t=69825Workaround:Install manually to%APPDATA%\\Roaming\\FreeCAD\\Mod.After editing some preferences FreeCAD uses a different File Selection DialogSee also in the Linux section andhttps://forum.freecadweb.org/viewtopic. ... 40#p498240.Workaround:a) Open the Parameter editor from the Tools menub) Navigate to BaseApp/Preferences/Dialogc) Create a boolean parameter named: DontUseNativeDialog and set it to true.Chocolatey installation problemsWorkaround:See thisforum post.[WinError 127] The specified procedure could not be found, followed by a path to \"shiboken2\".This is caused by having installed multiple versions of python, seehttps://forum.freecadweb.org/viewtopic. ... 12#p491312Solution:remove all but one Python versions. including their config files in %APPDATA%\\Roaming, see also the question below \"FreeCAD does not start or doesn't open certain workbenches\".The change from Qt4 to Qt5 can cause issues on Windows:wmayerwrote:\u2191Fri May 03, 2019 11:17 amThe responsible change that could explain the behaviour is the move from Qt4 to Qt5. Qt5 has a module QtOpenGL kept for backward compatibility but it's recommended not to use it and instead to port old code to the new API. At the beginning when we moved to Qt5 we used this module but it caused several problems and we then ported our code using the recommended API.Under the hood the implementation of OpenGL support in Qt5 has changed a lot and it's hard to say what at the end is responsible if something doesn't work. But as said above in most cases it's the graphic driver that causes problems.For more information also have a look here:https://doc.qt.io/qt-5/windows-requirem ... cs-driversMaybe you can get it to work by setting the variable QT_OPENGLWorkaround:If you face weird behaviour concerning mouse movements, menus disappearing, black windows, try the Qt4 variant of thedevelopment version.Important Note:The Win 0.19_pre QT4 version is getting old. During 0.19 some C++ stuff was added that the QT4/VS2013 libpack does not support. So there will be no further updates beyond the version that's on the above mentioned release page as of this date (FreeCAD_0.19.17352_x64_LP_11.11_PY2QT4-WinVS2013.7z)Windows display driverThere are issues with Radeon graphic cards. If your objects show transparency where they should not, it may be caused by the Radeon driver.Workaround:Rollback to an earlier driver graphic card driver version.SirSpamalotwrote:\u2191Tue Aug 28, 2018 10:46 pmI have a Radeon RX 460 card.  It appears that I updated the driver on July 23, 2018. The updated driver was version 24.20.12019.1010  (from Radeon Driver Package 18.7.1).  I rolled it back to the version that was previously installed, 21.19.407.0, and that resolved the problem.  I then rolled it forward to 24.20.11016.4 (from Radeon Driver Package 18.5.1) and I still don't have the problem.  Yay!Here is another report of issues with a Radeon 5470 and a driver solving it:https://forum.freecadweb.org/viewtopic. ... 44#p264835A user from the german forum has successfully installed the current driver version 18.12.2 including. Relive f\u00fcr his Radeon R9 380.Radeon Vega 64is said to be working with driver version 18.50.11.01-190109a-337968E-RadeonSoftwareAdrenalin2019. Seehttps://forum.freecadweb.org/viewtopic. ... 40#p281540Windows: screen going blackThis is again a display driver issue in connection with Qt5.Workaround 1:Try a Qt4 version of Freecad from thedevelopment versions.Workaround 2:Use a different version of opengl32.dll as described inthis post.FreeCAD doesn't start after installFreeCAD won't run in Windows 7 if you have \"Classic View\" enabled.Workaround:According tothis topicswitching to the \"Aero\" theme helps.View keeps spinning and/or zoomingWorkaround 1:Make sure you disconnect all additional devices, such as Joysticks. Seehttps://forum.freecadweb.org/viewtopic.php?f=3&t=36712Workaround 2:There was one case reported where leftovers from an autodesk installation caused such behaviour and the registry had to be cleaned; seehttps://forum.freecadweb.org/viewtopic. ... 03#p476992(German).The code execution cannot proceed because xxxx was not foundWhen trying to run 0.19_pre on Windows thisoutput has been reported. This is due to FreeCAD not finding relevant .dllsWorkaround 1:According to the same thread:Either you copy all dlls from the libpack's bin directory to FreeCAD's bin directory or to save disk memory set the PATH environment variable to include the libpack's bin directory.Workaround 2:According tohttps://forum.freecadweb.org/viewtopic. ... 18#p389721, you may check if the missing dll is provided by Micrososft. Download and install it.Crash in 0.18.4 when using Arch material toolseehttps://forum.freecadweb.org/viewtopic.php?f=23&t=36806Solution:Use 0.18.5 or latest 0.19Settings for HiDPI displaysseehttps://forum.freecadweb.org/viewtopic. ... 58#p366158Solution:1. Close FreeCAD2. Right click on the desktop shortcut for FreeCAD3. Properties4. Go to \"Compatibility\" tab5. \"Change high DPI settings\"6. Enable the option \"Use this setting to fix scaling problems for this program instead of the one in Settings\"7. Click OK to close dialogs8. Launch FreeCAD again (from the shortcut)Freecad does not start or does not open a new file or 3d-viewIt was reported with multiple graphics cards forNvidia Optimus hybridandAMD Radeongraphics cards.This can occur all of a sudden if some other software is installed.On these hybrid systems applications can use both graphic cards. They use in standard mode only the internal Intel HD, and delegate accellerated operations to the Nvidia card.See also thisposts in the german forumandthis onewith detailed descriptions.Solution (Nvidia):You have to correct a misconfiguration of the driver settings. Please add freecad executables to the programs which need 3d-acceleration. You can use the right mouse context menu and select execution with Nvidia. See alsoNvidia knowledgebaseSolution (AMD Radeon):Similar as above configure on which graphics card FreeCAD runs; seehttps://forum.freecadweb.org/viewtopic. ... 04#p489133Crash in Draft or Arch workbenchAccording to the research in the topicDraft WB crashes in 0.19.22670it is again an OpenGL issue.Solution:No solution yet.FreeCAD does not start; an error is shown in the log:Code:Select allLog: Cannot create directory C:\\Users\\nonAsciiUserName\\AppData\\Roaming\\FreeCAD\\webdatapersistent. Error: FILE_ERROR_ACCESS_DENIED.This can be caused by a username with non ASCII characters, such as Korean, Cyrillic.Solution:Start FreeCAD from a username with ASCII characters only.FreeCAD does not start or doesn't open certain workbenches, message \"%1 is not a valid Win32 application\"The reason is a not matching Python version in%APPDATA%\\Roaming\\Python\\Python38References:https://forum.freecadweb.org/viewtopic.php?t=49814https://forum.freecadweb.org/viewtopic. ... 60#p447360Solution:Remove the complete folder or at least%APPDATA%\\Roaming\\Python\\Python38\\site-packagesFreeCAD takes very long on startupThis can be caused by an unconnected network, seehttps://forum.freecadweb.org/viewtopic. ... 18#p450693in German forum.Solution:Remove the unconnected network.Numerals are displayed in an unreadable fontReferences:https://forum.freecadweb.org/viewtopic. ... 20#p382929https://forum.freecadweb.org/viewtopic. ... 84#p508884Solution:You have to set the correctLanguage for non-Unicode programs. Go into clock and region settings; click on Formats then change to chosen language and restart.MacOSMacOS: FreeCAD can't be opened, because it is from an unidentified developerMacOS Catilina (10.15): FreeCAD.app\u201d can\u2019t be opened because its integrity cannot be verifiedSolution:Depending on your system settings there are different things you can do:Rightclick on the app and select \"Open\". Then you get a dialog where you can confirm to open anyway.According tothis postthe quarantine flag has to be removed:Code:Select allsudo xattr -d com.apple.quarantine /Applications/FreeCAD.appAccording tothis postthe system settings can be changed:1. Open System Preferences2. Open Security & Privacy3. Unlock to make changes4. This makes active the two buttons midway down and you can selected bottom button 'App Store and identified developers'Now you may open FreeCAD in the way described in the points directly above.MacOS: freezing for about a minute on MacOS Mojave (10.14)Opening a system dialog on these systems can take extremely long.Workaround 1:start FreeCAD from a console or batch file.Seehttps://forum.freecadweb.org/viewtopic.php?f=4&t=31343andhttps://forum.freecadweb.org/viewtopic. ... 05#p329405for details.Workaround 2:create an alias to the executable, seehttps://forum.freecadweb.org/viewtopic. ... 05#p406100.1. Navigate to the \"Applications\" folder or whereever the directory containing the FreeCAD app is.2. Right click on the FreeCAD Application and select \"Show Package Contents\". (Note: a package is really just a directory of files that is double clickable to launch the app). This allows you to navigate down into the subdirectories.3. Open the Contents folder.4. Open the MacOS folder.5. Right-click on FreeCAD executable and select \"Make Alias\"6. Move that \"FreeCAD alias\" to your desktop or another place of your desire, from where you can start it with a double clickWorkaround 3:add/modify the certificate associated with FreeCAD, seehttps://forum.freecadweb.org/posting.ph ... 3#pr406476. This workaround can help if the previous causes issues with menues disappearing or not working.Open a terminal, cd to the directory with the FreeCAD application (or use the full path) and enter this:Code:Select allcodesign --force --deep -s - FreeCAD.appWorkaround 4:Remove FreeCAD.app from macOS Preferences > Security & Privacy > Privacy tab > Accessibility menu item;click Deny if prompted by macOS to grant FreeCAD access to \"whatever it is called\" that adds FreeCAD to that list in the first place.MacOS: Reboot on certain operationsIt was reported inone casethat FreeCAD rebooted while working in FreeCAD.Solution: This is not a FreeCAD issue. It was caused by an overful Desktop folder. For details see the linked forum post.MacOS: The desktop or another 3D image is shining throughWorkaround 1:Seehttps://forum.freecadweb.org/viewtopic. ... 10#p422710. After starting FreeCAD open a file from the recent files list. You can close it immediately and open a file via menu->open.Workaround 2:Seehttps://forum.freecadweb.org/viewtopic. ... 83#p422783. It seems to happen if PartDesign is the default workbench to start in. Change the default to Start workbench and switch to PartDesign later.Enable macos native dark mode on MacOS:Solution:Run this in Terminal.app:Code:Select alldefaults write freecad NSRequiresAquaSystemAppearance -bool FALSEMain window is empty(after having installed dark mode)Removing config files doesn't help.Workaround 1:Revert from dark mode withCode:Select alldefaults write freecad NSRequiresAquaSystemAppearance -bool TRUESeehttps://forum.freecadweb.org/viewtopic. ... 13#p500413.SOLVED:FreeCAD 0.19 doesn't run on MacOS Big SurWorkaround 1: Use FreeCAD 0.18.Workaround 2: Compile yourself using Homebrew, see e.g.https://forum.freecadweb.org/viewtopic. ... 63#p444758. Alas this will leave you with an outdated version."
},  {
    "author": "Hickonam",
    "date": "PostbyHickonam\u00bbSun Dec 29, 2024 7:06 pm",
    "content": "Good day community members. Just started using freecad recently (never used CAD software before) and came along a certain problem, can't seem to find solution anywhere, perhaps someone can help.So, I want to create some kind of bowl shaped object where the half of it would be higher than the other one, but the problem is that i created the object using two sketches and later revolved them via axis and fused them together to get this shape. It seems the only way i can smooth out the object so it would blend smoothly and create round edges while not loosing the height differences is to change it in 3d environment while perhaps connecting edges and smoothing them out with Curve plugin, but can't seem to come up with any solutions, the angles of the blending doesn't matter, what matters is to keep the bowlish shape and this height difference.I thank anyone in advance who will contribute to help me find a solution.OS: Windows 11 build 22631Architecture: x86_64Version: 1.0.0.39109 (Git) CondaBuild type: ReleaseBranch: (HEAD detached at 1.0.0)Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1Locale: English/Europe (en_150)Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt defaultInstalled mods:* A2plus 0.4.68* Curves 0.6.53* Lithophane"
},
{
    "author": "Shalmeneser",
    "date": "PostbyShalmeneser\u00bbSun Dec 29, 2024 7:59 pm",
    "content": "File ?"
},
{
    "author": "freedman",
    "date": "Postbyfreedman\u00bbSun Dec 29, 2024 8:07 pm",
    "content": "Did you try to fillet?"
},
{
    "author": "Pete_W",
    "date": "PostbyPete_W\u00bbSun Dec 29, 2024 9:45 pm",
    "content": "A possibility?"
},
{
    "author": "ferozerashid",
    "date": "Postbyferozerashid\u00bbSun Dec 29, 2024 10:18 pm",
    "content": "Two different sectionsstrategically distributed around the orbit made a smooth transition. Fine tuning can be done by relocating those cross-section.ArtisticBowl.png (128.31 KiB) Viewed 88 timesAnother option I was thinking about was BlendCurve/BlendSolid from Curves wb. Might be an overkill!"
},
{
    "author": "papyblaise",
    "date": "Postbypapyblaise\u00bbMon Dec 30, 2024 9:28 am",
    "content": "you put the cutting profile in the same plane as the main profile to avoid \"stairs\""
},
{
    "author": "hammax",
    "date": "Postbyhammax\u00bbMon Dec 30, 2024 12:36 pm",
    "content": "... an oblique \"smooth\" bowl by PartWB Sweep and brute force tangency:bowl_Pw_2.PNG (92.77 KiB) Viewed 5 times"
}
]

